### ISSUE TITLE
Support different length of radiotap header

### ISSUE THREAD

**Issue by kaiyuhou** [nprint/nprint#26]
I just noticed that radiotap header is possible to have variant header lengths captured from different devices. For example, all the radiotap frames captured on my devices have a header length of 56 bytes. (That's why I didn't notice this problem before.) But I recently notice the length is 26 for some frames captures from old 802.11 adaptors. I think we should support variant lengths for different radiotap structures.

I found there is a good document site about radiotap header: https://www.radiotap.org/
And they also provide an open-source parser for radiotap: https://github.com/radiotap/radiotap-library

**Comment by JordanHolland** [comment]
Hmm.. do you have any idea of the variability? i.e. is it just those two values, or are there a large number of possible options?

**Comment by kaiyuhou** [comment]
Just finished a very busy academic quarter. I will try to mimic what you have done to the TCP options and try to submit a PR recently.

**Comment by JordanHolland** [comment]
Bumping. Any updates on this?
