### ISSUE TITLE
Installation Error on MacOS

### ISSUE THREAD

**Issue by ghost** [nprint/nprint#27]
When I run `./configure && make && make install` I receive this error:
 `src/nprint.cpp:7:10: fatal error: 'argp.h' file not found
#include <argp.h>
         ^~~~~~~~
1 error generated.
make[1]: *** [src/nprint.o] Error 1
make: *** [all] Error 2
` 
even though I have installed argp with `brew install argp-standalone`. For reference, I am using an M1 MacBook.

**Comment by JordanHolland** [comment]
Did `argp-standalone` install correctly? Do you have the full output of the steps? It may be difficult for me to reproduce without an M1 if that is the issue.

**Comment by ghost** [comment]
Here is my output of `brew reinstall argp-standalone`:

`==> Downloading https://ghcr.io/v2/homebrew/core/argp-standalone/manifests/1.3-1
Already downloaded: /Users/*/Library/Caches/Homebrew/downloads/808d585cbec55c7a8a8c1eafb16766516a26ce59e999e7204d3c8c1cf5b78518--argp-standalone-1.3-1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/argp-standalone/blobs/sha256:88
Already downloaded: /Users/*/Library/Caches/Homebrew/downloads/262824fe79d7d3259e76b7f69f07e936080b8ad7bcfe88f001ef39e053659eba--argp-standalone--1.3.arm64_big_sur.bottle.1.tar.gz
==> Reinstalling argp-standalone 
==> Pouring argp-standalone--1.3.arm64_big_sur.bottle.1.tar.gz
🍺  /opt/homebrew/Cellar/argp-standalone/1.3: 6 files, 74.9KB`

If you would like me to uninstall and then fresh install I can try that as well.

**Comment by JordanHolland** [comment]
Hmm. I was just able to do a fresh install on Mac OS Big Sur. Do you know where `argp `is being installed? We may be looking in the wrong directory when linking.

We link using the following on Darwin (in [configure.ac](https://github.com/nprint/nprint/blob/master/configure.ac)
```
        [darwin*],
        [
         WRAPPER_CPPFLAGS="$WRAPPER_CPPFLAGS -I/usr/local/include"
         WRAPPER_LDFLAGS="$WRAPPER_LDFLAGS -largp -L/usr/local/lib"
        ])

AC_SUBST([WRAPPER_CPPFLAGS])
AC_SUBST([WRAPPER_LDFLAGS])
```

Hopefully this gets us on the right track.

**Comment by ghost** [comment]
For additional context, I am on Mac OS Big Sur 11.5.2.

I believe my `argp-standalone` is being installed in `/opt/homebrew/Cellar/argp-standalone/1.3`. This is what my output is for `ls -lsa /opt/homebrew/Cellar/argp-standalone/1.3`:

```
total 40
 0 drwxr-xr-x  8 username  admin   256 Aug 10 21:30 .
 0 drwxr-xr-x  3 username  admin    96 Aug 10 21:30 ..
 0 drwxr-xr-x  3 username  admin    96 Feb 23  2004 .brew
24 -rw-r--r--  1 username  admin  9917 Feb 23  2004 ChangeLog
 8 -rw-r--r--  1 username  admin   898 Aug 10 21:30 INSTALL_RECEIPT.json
 8 -rw-r--r--  1 username  admin    83 Feb 23  2004 TODO
 0 drwxr-xr-x  3 username  admin    96 Feb 23  2004 include
 0 drwxr-xr-x  3 username  admin    96 Feb 23  2004 lib
```

**Comment by JordanHolland** [comment]
does `argp.h@` exist in `/usr/local/include`?
does `libargp.a@` exit in `/user/local/lib`?

**Comment by ghost** [comment]
No, neither of those exist in those locations.

**Comment by JordanHolland** [comment]
Interesting. That's typically the default installation for brew. For example, when I just did a fresh install (on Big Sur 11.4) the installation worked fine. 

Either of these options should work:
1. install argp / move the libraries to the place `configure.ac` is looking for
2. install from source by changing `configure.ac` to look in the correct directory.

**Comment by ghost** [comment]
Thanks for the clarification. I edited the relevant lines in `configure.ac`:
```

        [darwin*],
        [
         WRAPPER_CPPFLAGS="$WRAPPER_CPPFLAGS -I/opt/homebrew/Cellar/argp-standalone/1.3/include"
         WRAPPER_LDFLAGS="$WRAPPER_LDFLAGS -largp -L/opt/homebrew/Cellar/argp-standalone/1.3/lib"
        ])

AC_SUBST([WRAPPER_CPPFLAGS])
AC_SUBST([WRAPPER_LDFLAGS])
```
However, I then received a different error:
```
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /Users/username/Downloads/nprint-1.2.0/build-aux/missing aclocal-1.16 
/Users/username/Downloads/nprint-1.2.0/build-aux/missing: line 81: aclocal-1.16: command not found
WARNING: 'aclocal-1.16' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
make: *** [aclocal.m4] Error 127
```

So I ran ``brew install automake`` and tried again and it seemed to proceed but it ended with ``make[1]: Nothing to be done for `install-data-am'.``

**Comment by JordanHolland** [comment]
You'll need to reconfigure as you've changed the configure input. 

Did you run `./configure`?

If that doesn't work you can try 

`autoreconf -f`
`./configure`
`make`

**Comment by ghost** [comment]
Previously, I was running `./configure && make && sudo make install`.

I just tried the second method you suggested as well but either way after I run `sudo make install` it ends with the same ``make[1]: Nothing to be done for `install-data-am'.``

**Comment by JordanHolland** [comment]
Can we just force brew to install `argp` to the place we look for by default to see if that works?

**Comment by JordanHolland** [comment]
Bumping this to see if this was fixed through nPrintML install and if we can close this issue.

**Comment by ssgu321** [comment]
I'm having this same issue. I have a mac with the apple silicon, and the [homebrew page](https://docs.brew.sh/Installation) says that it downloads homebrew and corresponding applications into '/opt/homebrew'. I tried both solutions and I got the same error for changing the paths in configure.ac. `WARNING: 'aclocal-1.16' is missing on your system.`

As for moving the argp.h and libargp.a files to /usr/local, I do not have an /include or /lib directory, so I tried running mkdir to create them, but I only have read access to /usr/local directories. I tried to grant myself access by changing the owner, but I got an error. 
`chown: /usr/local/: Operation not permitted`

**Comment by Earthwater** [comment]
Having issues as list above , you may refer to the following to solve it:

First, modify the `configure.ac` file to change as the following:
```
[darwin*],
        [
         WRAPPER_CPPFLAGS="$WRAPPER_CPPFLAGS -I/opt/homebrew/Cellar/argp-standalone/1.3/include"
         WRAPPER_LDFLAGS="$WRAPPER_LDFLAGS -largp -L/opt/homebrew/Cellar/argp-standalone/1.3/lib"
        ])
```

Second, install automake and autoconf by using the following commands:

```curl -OL http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz  
tar -xzf autoconf-2.69.tar.gz  
cd autoconf-2.69  
./configure && make && sudo make install
```

```curl -OL http://ftp.gnu.org/gnu/automake/automake-1.16.1.tar.gz  
tar -xzf automake-1.16.1.tar.gz  
cd automake-1.16.1  
./configure && make && sudo make install  
```

Then, run `./configure` and `make clean`, and then `make && sudo make install`, you will be fine

**Comment by JordanHolland** [comment]
Thanks @Earthwater for the fix, are you on the new apple silicon as well?

**Comment by ssgu321** [comment]
@Earthwater Thanks! This works for me.

**Comment by Earthwater** [comment]
@JordanHolland Sure, and users with similar puzzles can refer to this solution.
