### ISSUE TITLE
ICMP headers contain values not in [-1, 0, 1]

### ISSUE THREAD

**Issue by cmarkle85** [nprint/nprint#28]
In converting a PCAP to nprint using:
`nprint -P <pcap> -A -4 -6 -e -t -u -i -W <npt> -S`
The resultant nPrint contains non-ternary values for the ICMP ROH fields.

The packets do not appear to contain an ICMP header so I would have expected all values to be -1. The beginning ICMP fields are indeed -1. However, the ROH fields are all 0 except the following:
`icmp_roh_1      116
icmp_roh_2      104
icmp_roh_3       95
icmp_roh_4      100
icmp_roh_5      104
icmp_roh_6      111
icmp_roh_7      115
icmp_roh_8      116
icmp_roh_9       95
icmp_roh_10      51
icmp_roh_11      51
icmp_roh_16    -112
icmp_roh_17      -4
icmp_roh_18     -18
icmp_roh_19     102
icmp_roh_20     -72
icmp_roh_21      85`

The ROH field values are all the same for all packets in the PCAP (possibly not for packets with ICMP headers) as well as from PCAP to PCAP.

I'm analyzing the nprint file using python's pandas, though I doubt that would be the cause.

**Comment by JordanHolland** [comment]
Looks like memory being accessed incorrectly. Thanks for reporting it! Do you have an example of a pcap that is causing it?

**Comment by cmarkle85** [comment]
Jordan,

Thanks for the quick reply. Sorry, I can't provide the PCAP. But it has behaved this way on all the PCAPs that I've tried, so you should be able to replicate it on any PCAP you generate. If you can't replicate the behavior please let me know.

**Comment by JordanHolland** [comment]
I see. I'll take a deep look at this on Monday and let you know. Until then, if there is no ICMP traffic to consider, I would just disable the flag as a temporary workaround.

**Comment by JordanHolland** [comment]
Found the bug pretty quickly, had to do with a wrong `#define` in the ipv6 header that was causing the memory issue. The fix is pushed to the main branch, and will be fixed in the next release, hopefully after #3 is updated.
