### ISSUE TITLE
nPrint values do not seem to be correct

### ISSUE THREAD

**Issue by cmarkle85** [nprint/nprint#30]
nPrint appears to be reading the wrong bytes when determining the TCP source and destination ports. When reading bytes from the TCP header, it appears to read from the wrong location and ends up reading bytes from the sequence number instead.

The source port is read from the first 2 bytes of the sequence number, and the destination is read from the last 2. This is an offset of about +4 bytes from where it should be reading. This issue seems to persist to other fields as well. What is labeled as the sequence number is instead actually the acknowledgement number, which is off by 4-bytes from the sequence number.

This was discovered by directly comparing the values with those given in Wireshark.

The IP and MAC address fields seem to be correct. Not sure how many fields/headers are effected by this issue.

I'm not sure if this is related to the ICMP ROH issue (#28) or the PCAP reconstruction issue #3.

This was produced on:
Ubuntu 20.04
TShark (Wireshark) 3.2.3 (Git v3.2.3 packaged as 3.2.3-1)
tcpdump version 4.9.3
libpcap version 1.9.1 (with TPACKET_V3)
OpenSSL 1.1.1f  31 Mar 2020
nprint 1.2.0

**Comment by JordanHolland** [comment]
Thanks for the detailed issue. Quick question. What flags are you using?

**Comment by cmarkle85** [comment]
nprint -P test.pcap -A -4 -6 -e -t -u -i -W test.npt -S

**Comment by JordanHolland** [comment]
This is almost certainly an artifact from #28. If you haven't installed from source after e435a72 you will have errors for any protocols following the IPv6 header. If you don't want to install from source try disabling the `-6` flag and see if the bug persists.

**Comment by JordanHolland** [comment]
Checking to see if the commit above fixed this issue before pushing  a new release. Thanks

**Comment by cmarkle85** [comment]
This did indeed fix the issue.
