### ISSUE TITLE
Installation Error on Centos7.0

### ISSUE THREAD

**Issue by p197** [nprint/nprint#31]
![image](https://user-images.githubusercontent.com/34874499/138054335-48bdf6c0-c6bd-45cf-8b86-6e868d2812a6.png)
![image](https://user-images.githubusercontent.com/34874499/138054367-9171effd-ddd7-4800-b1ad-094b6cd9293b.png)

**Comment by JordanHolland** [comment]
Thanks for the issue. I'm on vacation for the next two weeks so this will not be resolved until I get back. In the meantime, the most likely culprit has to do with setting the `_BSD_SOURCE`  with something like

```
#ifndef __FAVOR_BSD
#define __FAVOR_BSD 2
#endif
#ifndef __USE_BSD
#define __USE_BSD
#endif
```

**Comment by p197** [comment]
Thanks

**Comment by JordanHolland** [comment]
Updating now. I have no easy way of testing the above to see if it works. We are working on an Ubuntu docker image that comes with nPrint and nPrintML pre-installed as a quick fix to get up and running. If you are able to find a fix (or if the above fix works) and you can submit a PR that would be incredibly helpful.
