### ISSUE TITLE
Extensive Other Protocols

### ISSUE THREAD

**Issue by ZKK4** [nprint/nprint#33]
nPrint only supports Ethernet, IPv4, IPv6, UDP, TCP, ICMP, and any corresponding packet payload which often used. But other protocols such as DNS, ARP, STP are impossible. The packets information with the above protocol is ignored when using nPrint. Will there be any loss of information for packets with the above protocols?

**Comment by JordanHolland** [comment]
Can you describe which "above" protocols you are talking about when asking about information loss?

For IPv4, UDP, TCP, and ICMP, the full header is used and there is no information loss. For IPv6, fixed headers are implemented and any other headers will be ignored. If you need more functionality for IPv6 please feel free to contribute! For payloads, only the number of bytes included in the `-p` flag will be included for each packet. If a packet contains a payload larger than the specified `-p` flag, those bytes will not be included in the nPrints. In most cases, these payloads will be encrypted anyways. 

DNS, ARP, and STP are not implemented, but that does not imply that they are impossible. As of now, if nPrint does not recognize the protocol it simply skips the packet altogether when processing a trace and these packets will not be included in the output. If you are interested in using nPrint for any of these protocols we encourage you to contribute to nPrint's development via a PR and we are happy to help!

**Comment by JordanHolland** [comment]
Can I close this issue?
