### ISSUE TITLE
working Problem in Ubuntu

### ISSUE THREAD

**Issue by devin-rom** [nprint/nprint#34]
can you give me the more instruction about how install nprint 
i did it in your instructions but nprint commands do not work plz 
i will post a message 
**make[1]: Entering directory '/home/meditech/pcapml-0.2.0'
make[1]: Leaving directory '/home/meditech/pcapml-0.2.0'
root@meditech-virtual-machine:/home/meditech/pcapml-0.2.0# make install
make[1]: Entering directory '/home/meditech/pcapml-0.2.0'
 /usr/bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c pcapml '/usr/local/bin'
make[1]: Nothing to be done for 'install-data-am'.**

**Comment by JordanHolland** [comment]
This looks like pcapml, not nPrint?

**Comment by devin-rom** [comment]
Plz send me how to install nprint

**Comment by nprint** [comment]
https://github.com/nprint/nprint/wiki/2.-Installation

**Comment by devin-rom** [comment]
I installed as you say in instructions is there different way for install nprint

**Comment by devin-rom** [comment]
Segmentation error is happened when convert .npt to .pcap only large files
