### ISSUE TITLE
What are the naming rules for datasets?

### ISSUE THREAD

**Issue by lei-rw** [nprint/nprint#38]
### What's up?

Hello, I downloaded your dataset from this website ' https://nprint.github.io/datasets.html 'and tested it with nprintml, but I don't understand its naming rules. As shown in the figure, I want to know the meaning of the serial number at the beginning and 'OFP', 'T1', '76' and 'tseq'.
![屏幕截图 2022-04-12 151516](https://user-images.githubusercontent.com/103157078/162902610-81616567-160f-4738-a33d-c09be6711e79.jpg)

### Due diligence

- [X] I have read the docs

**Comment by JordanHolland** [comment]
Before starting, it does seem that the dataset does not split completely as intended with`pcapml`. I will fix this when I get a chance.

> I want to know the meaning of the serial number at the beginning 

see [pcapML walkthrough](https://nprint.github.io/pcapml/walk.html)

> and 'OFP', 'T1', '76' and 'tseq'

These are directly copied from Nmap's probe names. See [here](https://nmap.org/book/osdetect-methods.html) and [here](https://nprint.github.io/benchmarks/device_fingerprinting/network_device_fingerprinting.html)

As for the dataset, you may get a better idea by running tshark on the `pcapML` encoded `pcapng`, as shown below

`$ tshark -r traffic.pcapng -T fields -e frame.comment`

```
273992,avtech-OFP-TICMP1
266095,huawei-OFP-TICMP1
264887,roku-OFP-TICMP1
264631,roku-OFP-TICMP1
264631,roku-OFP-TICMP0
262675,axis-OFP-TUDP0
262211,roku-OFP-TICMP1
262211,roku-OFP-TICMP0
261490,roku-OFP-TICMP1
261490,roku-OFP-TICMP0
```

which shows the `sampleID,label-probename` in the dataset. Again this doesn't seem to be correctly splitting, but the above should help explain what's going on.
