### ISSUE TITLE
[Question]: The number of packets after feature extraction is is less than the number of original packets

### ISSUE THREAD

**Issue by yuanlulu-14** [nprint/nprint#39]
### What's up?

Hi,
I installed nprint in my MacOS and used it to extract some pcap files including 10000 packets. But the number of packets is less than 10000. It is 9995 or 9990. I don't know which packets were dropped.

### Due diligence

- [X] I have read the docs

**Comment by JordanHolland** [comment]
There are a large number of reasons this could have happened, and the information above gives no insight into how to fix the problem.

A few ways to fix the issue
* use `tcpdump` to see if the packets get dropped.
* if `tcpdump` doesn't drop the packets, provide more information on the traffic, the command you ran, and the dropped packets.
