### ISSUE TITLE
[Bug]: …Seems nprint doesn't support centos

### ISSUE THREAD

**Issue by yue123161** [nprint/nprint#40]
### What did you do?

When i try to install nprintml in centos, it found those errors
src/packet/tcp_header.cpp: In member function 'virtual void TCPHeader::print_header(FILE*)':
src/packet/tcp_header.cpp:23:70: error: 'struct tcphdr' has no member named 'th_sport'
     fprintf(out, "TCPHeader: src_prt: %d, dst_prt: %d\n", ntohs(raw->th_sport),
                                                                      ^
src/packet/tcp_header.cpp:24:23: error: 'struct tcphdr' has no member named 'th_dport'
            ntohs(raw->th_dport));
                       ^
src/packet/tcp_header.cpp: In member function 'virtual uint32_t TCPHeader::get_header_len()':
src/packet/tcp_header.cpp:28:17: error: 'struct tcphdr' has no member named 'th_off'
     return raw->th_off * 4;
                 ^
src/packet/tcp_header.cpp: In member function 'virtual void TCPHeader::get_bitstring(std::vector<signed char>&, int8_t)':
src/packet/tcp_header.cpp:38:33: error: 'struct tcphdr' has no member named 'th_off'

### What happened?

it doesn't support centos

### Operating system

centos 7

### Version

1.2.1

**Comment by JordanHolland** [comment]
A few options:

* Use the [provided docker image](https://nprint.github.io/nprintml/docker.html) with `nprint` and `nprintml` already installed
* Attempt the fix in #31, and if it fixes the issue on centos open a PR to help improve the availability of nPrint on different platforms.
