### ISSUE TITLE
[Question]: i run ./configle ,there is a error,How can I solve this problem?

### ISSUE THREAD

**Issue by cinderhk** [nprint/nprint#43]
### What's up?

checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for pcap_loop in -lpcap... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for int32_t... yes
checking for int64_t... yes
checking for int8_t... yes
checking for size_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for inet_ntoa... yes
./configure: line 4206: WRAPPER_LDFLAGS: command not found
./configure: line 4207: WRAPPER_CPPFLAGS: command not found
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking dependency style of g++... gcc3
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
make  all-am
make[1]: Entering directory `/root/nprint-1.2.1'
depbase=`echo src/packet/tcp_header.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I.  -Iinclude/ -Iinclude/io/ -Iinclude/packet/ -pedantic -Wall -std=gnu++11    -g -O2 -MT src/packet/tcp_header.o -MD -MP -MF $depbase.Tpo -c -o src/packet/tcp_header.o src/packet/tcp_header.cpp &&\
mv -f $depbase.Tpo $depbase.Po
In file included from /usr/include/bits/byteswap.h:35:0,
                 from /usr/include/endian.h:60,
                 from /usr/include/sys/types.h:216,
                 from /usr/include/netinet/tcp.h:66,
                 from include/packet/tcp_header.hpp:11,
                 from src/packet/tcp_header.cpp:8:
src/packet/tcp_header.cpp: In member function ‘virtual void TCPHeader::print_header(FILE*)’:
src/packet/tcp_header.cpp:23:70: error: ‘struct tcphdr’ has no member named ‘th_sport’
     fprintf(out, "TCPHeader: src_prt: %d, dst_prt: %d\n", ntohs(raw->th_sport),
                                                                      ^
src/packet/tcp_header.cpp:24:23: error: ‘struct tcphdr’ has no member named ‘th_dport’
            ntohs(raw->th_dport));
                       ^
src/packet/tcp_header.cpp: In member function ‘virtual uint32_t TCPHeader::get_header_len()’:
src/packet/tcp_header.cpp:28:17: error: ‘struct tcphdr’ has no member named ‘th_off’
     return raw->th_off * 4;
                 ^
src/packet/tcp_header.cpp: In member function ‘virtual void TCPHeader::get_bitstring(std::vector<signed char>&, int8_t)’:
src/packet/tcp_header.cpp:38:33: error: ‘struct tcphdr’ has no member named ‘th_off’
     tcp_header_byte_size = raw->th_off * 4;
                                 ^
In file included from /usr/include/bits/byteswap.h:35:0,
                 from /usr/include/endian.h:60,
                 from /usr/include/sys/types.h:216,
                 from /usr/include/netinet/tcp.h:66,
                 from include/packet/tcp_header.hpp:11,
                 from src/packet/tcp_header.cpp:8:
src/packet/tcp_header.cpp: In member function ‘std::string TCPHeader::get_port(bool)’:
src/packet/tcp_header.cpp:73:42: error: ‘struct tcphdr’ has no member named ‘th_sport’
         return std::to_string(ntohs(raw->th_sport));
                                          ^
src/packet/tcp_header.cpp:75:42: error: ‘struct tcphdr’ has no member named ‘th_dport’
         return std::to_string(ntohs(raw->th_dport));
                                          ^
src/packet/tcp_header.cpp: In member function ‘virtual uint32_t TCPHeader::get_header_len()’:
src/packet/tcp_header.cpp:29:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[1]: *** [src/packet/tcp_header.o] Error 1
make[1]: Leaving directory `/root/nprint-1.2.1'
make: *** [all] Error 2

### Due diligence

- [X] I have read the docs

**Comment by JordanHolland** [comment]
What OS is this?

**Comment by JordanHolland** [comment]
nPrint and nPrintML have not been tested or do we expect them to run on Windows. A docker container has been released with the software installed that may be of use: https://nprint.github.io/nprintml/docker.html
