### ISSUE TITLE
nPrint supports input in csv format?

### ISSUE THREAD

**Issue by Cherry1210** [nprint/nprint#44]
### What's up?

nPrint supports input in csv format, what does the specific input form look like? Is there a sample csv please? Thanks

### Due diligence

- [X] I have read the docs

**Comment by JordanHolland** [comment]
Thanks for reaching out. I don't have a sample csv on-hand, but the functionality was built to consume [Zmap scans](https://github.com/zmap/zmap). Specifically, it is built to consume the [hex-encoded](https://github.com/zmap/zmap/blob/main/src/output_modules/module_csv.c#L70) csv [output](https://github.com/zmap/zmap/blob/main/src/output_modules/module_csv.c) of a zmap scan. Any csv-file with a hex-[encoded packet in the 3rd (0-indexed)](https://github.com/nprint/nprint/blob/2444f832baf17cd2ca4d91d4e30b4ae9338532e7/src/io/stringfile_parser.cpp#L24) column should work.
