### ISSUE TITLE
[Question]:About naming of PCAP files in intrusion detection task.

### ISSUE THREAD

**Issue by DmrS5** [nprint/nprint#45]
### What's up?

I found that the number seems to be random. Are there any rules for naming?

![图片](https://github.com/nprint/nprint/assets/126075324/1c92fc0f-b852-420e-ae4a-02cabf61e1af)

### Due diligence

- [X] I have read the docs

**Comment by JordanHolland** [comment]
https://nprint.github.io/pcapml/walk.html - Should help. There is also a readme with the dataset that describes the naming conventions.

**Comment by DmrS5** [comment]
Thanks a lot. That really help.
