### ISSUE TITLE
[Question]: about os detective train dataset

### ISSUE THREAD

**Issue by odysseus1001** [nprint/nprint#46]
### What's up?

 if it would be possible for you to share the Active Device Fingerprinting data set used in your experiments or any pre-trained models you might have？I am keen to further explore this topic and would like to delve deeper into your research.

### Due diligence

- [X] I have read the docs

**Comment by JordanHolland** [comment]
https://drive.google.com/drive/folders/158Lwb9TwopIJ0lGPuFik5744qPiqrg9F

Enjoy!
